project:
  type: website

website:
  title: "Filling in the Gaps"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
        
format:
  html:
    theme: flatly
    css: styles.css
    title-block-banner: images/new_havn_styled.jpeg
    render-math-as: svg



